{
 "title": "UPS",
 "tags": [ "nut" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ups",
    "label": "UPS",
    "query": "label_values(network_ups_tools_device_info, ups)"
   }
  ]
 },
 "panels": [
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{mfr}} {{model}}"
    }
   ]
  },
  {
   "title": "Nominal Power",
   "type": "stat",
   "description": "Indicates the approximate maximum load the UPS is designed to support under normal conditions",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_power_nominal{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Nominal Output Frequency",
   "type": "stat",
   "description": "Indicates the standard operating frequency of the UPS when supplying power to connected devices",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_output_frequency_nominal{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Nominal Output Voltage",
   "type": "stat",
   "description": "Standard voltage that the UPS is designed to provide to connected devices when running on battery power or through its inverter",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage_nominal{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Low voltage transfer point",
   "type": "stat",
   "description": "When the input voltage drops below this value, the UPS will switch to battery mode to protect connected equipment from undervoltage conditions",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_transfer_low{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "High voltage transfer point",
   "type": "stat",
   "description": "When the input voltage rises above this value, the UPS will switch to battery mode to protect against overvoltage conditions",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_transfer_high{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{ups=\"$ups\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_power{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_beeper_status{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_power{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge / Battery Charge Low",
   "type": "timeseries",
   "description": "If the Battery Charge drops below the Battery Charge Low value, the UPS signals a low battery warning and may prepare for shutdown",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}",
     "legendFormat": "{{ups}} charge"
    },
    {
     "expr": "network_ups_tools_battery_charge_low{ups=\"$ups\"}",
     "legendFormat": "{{ups}} charge low"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "description": "Estimated remaining runtime of the UPS based on the current load and battery charge level",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "timeseries",
   "description": "Estimated remaining runtime of the UPS based on the current load and battery charge level",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Frequency",
   "type": "gauge",
   "description": "Current frequency of the incoming AC power from the mains",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_frequency{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "description": "Current voltage of the incoming AC power from the mains",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Frequency",
   "type": "gauge",
   "description": "Current output frequency",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_output_frequency{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "description": "Current output voltage",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_output_voltage{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}