---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dind
    image: scalified/dind
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
