---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: dind
    image: scalified/dind
    privileged: true
    cgroupns_mode: host
    volumes:
      - /home/runner/dind:/var/lib/docker
provisioner:
  name: ansible
verifier:
  name: ansible
